### ISSUE TITLE
Attched file no loger displayed as link

### ISSUE THREAD

**Issue by pan-havranek** [formtools/module-export_manager#22]
Hi!

The pop-up showing exported data no longer displays uploaded file name as a link. So, to download/see that file you have to go back to the form view screen, enter entry details and download/see file from there.

**Comment by benkeen** [comment]
Thanks @pan-havranek, I'll check this out. I think this is a bug with the File Upload module.

**Comment by benkeen** [comment]
Sorry for the long wait on this. I was just looking at it tonight and it's rather fiddly. I mean it's easy to change, but not to change for specific export types. To my mind, HTML format should show the filenames as links - that makes sense. CSV, XML and Excel, however, should just show the full URL I think... 

I suspect that before it just always outputted links for all of them, but I want to find a better way to handle it. Should figure it out tomorrow. It's need updates to both the Export Manager & File Upload modules.

Keep you posted.

**Comment by pan-havranek** [comment]
Thanks for looking at it. You're right - it makes sense that CSV, XML and Excel show the link rather be a link. In HTML it would be handy to have the instant access to linked files. I use this in my daily work and receive often attached files. So, I'm crossing my fingers for restoring this functionality. Thanks.

**Comment by benkeen** [comment]
Yeah, I totally agree. This is needed.

I'll add in a "Content type" setting for Export Groups within the Export Manager with "html" and "text" radio options. For new installations, all the Export Groups will have it set to "text" by default except for the HTML/Printer-friendly Export Group. I can use that to figure out whether to display the HTML link or not (and hopefully anything else that crops up along these lines). 

Keep you posted...!

**Comment by benkeen** [comment]
All fixed. I'll update the doc tonight, but you can try it out by upgrading your Export Manager version to 3.1.0, and your File Upload module to 2.2.4. 

It will *probably* work right away, but in case it doesn't, you may need to edit your "HTML/Printer-friendly" Export Group and set the "Content Type" field to HTML.
