### ISSUE TITLE
Remove set_time_limit(300);

### ISSUE THREAD

**Issue by guitarbeard** [formtools/module-export_manager#26]
This is blocking the export of large databases. The application should use php.ini to set the time limit and not magic numbers hidden in code here: https://github.com/formtools/module-export_manager/blob/master/code/Module.class.php#L597

**Comment by benkeen** [comment]
Hey @guitarbeard, thanks! Good idea. The problem is that some systems have very low settings for that var, so the setting here was intended to mitigate that/.

But what we need is probably a setting in the UI. Perhaps even a Form Tools core setting, rather than something specific to this module.

**Comment by benkeen** [comment]
Also see: https://github.com/formtools/core/issues/636

**Comment by benkeen** [comment]
I ended up making it just configurable within the module rather than with the main script. I figure it's possible you'd want different timeouts for different activities. I'll release 3.2.0 now.

**Comment by guitarbeard** [comment]
Awesome! Glad I could help out and thank you for all the work you do!
